### PR TITLE
[NEW] IA ANAGRAM

### PR DESCRIPTION
**Pull request by tynitoon**
This IA will find all anagram and subanagram into a sentence or a word.

### CODE REVIEW

**Comment by Pierohub** [comment]
Is that PHP?

**Comment by tynitoon** [comment]
Php part is just a script to launch if you want to add new language_database

**Comment by tynitoon** [comment]
IA is now ready

**Review by stephanembl — COMMENTED** [review]
The presence of a PHP script is bothersome... Even for a dev tool. 
Also, having to add lists of words is sketchy and heavy. An API IA would make more sense, probably

**Pull request closed without merging**
