### PR TITLE
[CONTRIB Encryption] caesar

### PR DESCRIPTION
**Pull request by myrosblog**
Hi, 

Related to https://github.com/Qwant/Instant-Answers/issues/31,

I created the Caesar encryption module, by default the offset is 13, but you can specify any number :
capture d ecran 2017-10-18 a 11 59 09

capture d ecran 2017-10-18 a 11 58 43

Thanks,
Florian

### CODE REVIEW

**Comment by stephanembl** [comment]
Hi! Thank your for your contribution :) We will look into merging it in next week's release :) 👍

**Comment by stephanembl** [comment]
Hey! Sorry, we had to delay our roadmap regarding Open Source Instant Answers as we're rolling out new stuff. We're looking into merging this today, and it will go to production with the next release (soon)  :) Thank you!

**Comment by stephanembl** [comment]
Hello @floriancourgey !
Sorry to get back to you so late, even and more sorry because it's bad news... We tested your contribution for a while and it turns out there are a lot of false positive with the word "cesar". Some people wanting information about caesar salad, or the caesar palace, or some people (cesar azpilicueta for example) are going to get an unwanted and unrelated instant answer.

We're putting that on the shelves for now, but we'll work on finding a solution! Thanks again for your contribution.

**Comment by myrosblog** [comment]
Hi @stephanemombuleau ,

No problem, I get it! Happy to help :)

Feel free to give more ideas here https://github.com/Qwant/Instant-Answers/wiki

**Pull request merged**
